### ISSUE TITLE
Setup file generation order issue

### ISSUE THREAD

**Issue by ar13pit** [tue-robotics/tue-env#521]
`target_setup.bash` is generated only after exiting the main loop in `tue-install-impl.bash`, i.e., in `tue-functions.bash` towards the end of a `tue-get` command by checking the list of installed targets and their dependencies.

This is too restrictive. The list of setup files to be sourced should be generated while processing each target but only written upon exiting the main loop in `tue-install-impl.bash`.

**Reason**
For a target like `gazebo`:
```yaml
- type: target
  name: gazebo-setup

- type: system
  name: gazebo9

- type: target
  name: gazebo_models
```

 we have skipped sourcing of its default variables by not sourcing `/usr/share/gazebo/setup.sh`. Adding this sourcing in `setup` would place the `setup` file of `gazebo` after the target `gazebo_models`, while it should be placed before `gazebo_models`.

My current hack is place the sourcing of `/usr/share/gazebo/setup.sh` in the `setup` of `gazebo_models`, which is undesirable.
